version: '3.8'

services:
  denis-db:
    container_name: denis-db
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: master
    ports:
      - "3125:5432"
    volumes:
      - auth_db_data_denis:/var/lib/postgresql/data

volumes:
  auth_db_data_denis:
